CREATE DATABASE IF NOT EXISTS `personnel`; -- 人员库
# ---------------------------------------- 人员 ----------------------------------------
CREATE TABLE IF NOT EXISTS `personnel`.`personnel_info`
(
    `import_id`                   varchar(255) NOT NULL COMMENT '导入ID',
    `personal_identifier`         varchar(255) COMMENT '个人标识 GRBS',
    `unit_code`                   varchar(255) DEFAULT NULL COMMENT '单位代码 DWDM',
    `unit`                        varchar(255) DEFAULT NULL COMMENT '单位 DW',
    `name`                        varchar(255) DEFAULT NULL COMMENT '姓名 XM',
    `position`                    varchar(255) DEFAULT NULL COMMENT '职务 ZW',
    `sex`                         varchar(10)  DEFAULT NULL COMMENT '性别 XB',
    `appointment_date`            date         DEFAULT NULL COMMENT '任职年月 RZNY',
    `native_place`                varchar(255) DEFAULT NULL COMMENT '籍贯 JG',
    `family_background`           varchar(255) DEFAULT NULL COMMENT '家庭出身 JTCS',
    `education_level`             varchar(255) DEFAULT NULL COMMENT '文化程度 WHCD',
    `birthday`                    date         DEFAULT NULL COMMENT '生日 SR',
    `enlistment_date`             date         DEFAULT NULL COMMENT '入伍年月 RWNY',
    `rating_date`                 date         DEFAULT NULL COMMENT '评级年月 PJNY',
    `graduate_college`            varchar(255) DEFAULT NULL COMMENT '毕业学院 BYXY',
    `graduation_date`             date         DEFAULT NULL COMMENT '毕业年月 BYNY',
    `military_rank`               varchar(255) DEFAULT NULL COMMENT '军衔 JX',
    `pilot_role`                  varchar(255) DEFAULT NULL COMMENT '正副驾驶 ZFJS',
    `flight_level`                varchar(255) DEFAULT NULL COMMENT '飞行等级 FXDJ',
    `current_aircraft_type`       varchar(255) DEFAULT NULL COMMENT '现飞机型 XFJX',
    `pxh`                         varchar(255) DEFAULT NULL COMMENT 'PXH',
    `code_name`                   varchar(255) DEFAULT NULL COMMENT '代号 DH',
    `bm`                          varchar(255) DEFAULT NULL COMMENT 'BM',
    `code_character`              varchar(255) DEFAULT NULL COMMENT '代字 DZ',
    `is_air_combat_commander`     varchar(255) DEFAULT NULL COMMENT '是否空战指挥员 SFKZZHY',
    `flight_outline`              varchar(255) DEFAULT NULL COMMENT '飞行提纲 FXTG',
    `lead_pilot`                  varchar(255) DEFAULT NULL COMMENT '长机 ZJ',
    `command_level_daytime`       varchar(255) DEFAULT NULL COMMENT '指挥水平（昼间） ZHSP_ZJ',
    `command_level_nighttime`     varchar(255) DEFAULT NULL COMMENT '指挥水平（夜间） ZHSP_YJ',
    `instructor`                  varchar(255) DEFAULT NULL COMMENT '教员 JY',
    `theoretical_instructor`      varchar(255) DEFAULT NULL COMMENT '理论教员 LLJY',
    `zbzt`                        varchar(255) DEFAULT NULL COMMENT 'ZBZT',
    `is_trainee`                  varchar(255) DEFAULT NULL COMMENT '是否学员 SFXY',
    `is_instructor`               varchar(255) DEFAULT NULL COMMENT '是否教官 SFJG',
    `qb`                          varchar(255) DEFAULT NULL COMMENT 'QB',
    `last_parachute_time_land`    date         DEFAULT NULL COMMENT '最后跳伞时间（陆） ZHTSSJ_L',
    `last_parachute_time_water`   date         DEFAULT NULL COMMENT '最后跳伞时间（水） ZHTSSJ_S',
    `modification_time`           date         DEFAULT NULL COMMENT '修改时间 XGSJ',
    `total_time_history`          varchar(255) DEFAULT NULL COMMENT '历年总时间 LNZSJ HH:mm',
    `total_time_current_year`     varchar(255) DEFAULT NULL COMMENT '本年总时间 BNZSJ HH:mm',
    `total_teaching_time_history` varchar(255) DEFAULT NULL COMMENT '历年任教时间 LNRJSJ HH:mm',
    PRIMARY KEY (`personal_identifier`)
);
