name: push-jar-to-maven-central
on:
  push:
    paths:
      # 只监听根路径 pom.xml 文件变化
      - pom.xml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      VERSION_CHANGED: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Get the version from pom.xml before and after commit
        id: version_check
        run: |
          # 获取提交前后的pom.xml版本信息，正则只匹配第一个<version>...</version>
          PREVIOUS_VERSION=$(git show HEAD~1:pom.xml | grep -oP '(?<=<version>)(.*?)(?=</version>)' | head -n 1)
          CURRENT_VERSION=$(cat pom.xml | grep -oP '(?<=<version>)(.*?)(?=</version>)' | head -n 1)
          
          # 如果版本变化了，标记为 true
          if [ "$PREVIOUS_VERSION" != "$CURRENT_VERSION" ]; then
            echo "Version changed: $PREVIOUS_VERSION -> $CURRENT_VERSION"
            $VERSION_CHANGED=true
          else
            echo "Version not changed"
            $VERSION_CHANGED=false

      - name: Download gpg public key
        run: gpg --keyserver keyserver.ubuntu.com --recv-keys ${{ secrets.GPG_PUBLIC_KEY_ID }}

      - name: Set up Graal JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'      # See 'Options' section below for all supported versions
          distribution: 'graalvm' # See 'Options' section below for all available distributions
          cache: 'maven'
          server-id: central
          server-username: ${{ secrets.MAVEN_USERNAME }}
          server-password: ${{ secrets.MAVEN_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build and deploy with Maven
        if: ${{ env.VERSION_CHANGED == true }}
        run: mvn -B -Dmaven.test.skip=true clean deploy


