name: test-compile
on:
  push:
    branches:
      - main

jobs:
  test-compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Graal JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'      # See 'Options' section below for all supported versions
          distribution: 'graalvm' # See 'Options' section below for all available distributions
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B -Dmaven.test.skip=true clean package
